### ISSUE TITLE
Issues with document titles (DHIS vs DHIS 2 vs DHIS2, etc)

### ISSUE THREAD

**Issue by mortenoh** [dhis2/dhis2-docs#103]
I see we still have a few issues with doc titles, probably would be good to update them all to match.

<img width="631" alt="screen shot 2016-07-27 at 13 18 29" src="https://cloud.githubusercontent.com/assets/84345/17173852/81fc1704-53fd-11e6-866d-8180ff33f17c.png">
<img width="503" alt="screen shot 2016-07-27 at 13 19 04" src="https://cloud.githubusercontent.com/assets/84345/17173849/81f632ee-53fd-11e6-82ed-54eabfff6d3a.png">
<img width="480" alt="screen shot 2016-07-27 at 13 19 10" src="https://cloud.githubusercontent.com/assets/84345/17173850/81f6e0ea-53fd-11e6-91e3-478a0fb83c27.png">
<img width="442" alt="screen shot 2016-07-27 at 13 19 15" src="https://cloud.githubusercontent.com/assets/84345/17173851/81f85ad8-53fd-11e6-802f-94c558265f9f.png">
<img width="496" alt="screen shot 2016-07-27 at 13 19 21" src="https://cloud.githubusercontent.com/assets/84345/17173853/81fc3d10-53fd-11e6-85a2-973d086b5ce8.png">
<img width="447" alt="screen shot 2016-07-27 at 13 19 26" src="https://cloud.githubusercontent.com/assets/84345/17173854/82009c0c-53fd-11e6-9bcb-b782bff36e93.png">

**Comment by jason-p-pickering** [comment]
Closed via 310bca85b69fd1010d54b573eff02a6be0a32383
