### ISSUE TITLE
Implementer links are broken

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-docs#105]
Hi Jason,

I hope you are doing well. While installing DHIS 2 from scratch on a local desktop at home I found out that the links of implementation guide of the 2.25 on our dhis2.org/documentation page were redirecting to a 404 - File not found page.

the urls are:
PDF: http://dhis2.github.io/dhis2-docs/master/en/implementer/dhis2_implementation_guide_en.pdf
html: http://dhis2.github.io/dhis2-docs/master/en/implementer/html/dhis2_implementation_guide_en.html
html single page: http://dhis2.github.io/dhis2-docs/master/en/implementer/html/dhis2_implementation_guide_en_full.html

Can we update these links?

Cheers,
Matthieu

**Comment by mrwine** [comment]
Links are now updated

**Comment by jason-p-pickering** [comment]
@mrwine thanks.
