### ISSUE TITLE
Contradiction in GML OU identifiers

### ISSUE THREAD

**Issue by hardingt** [dhis2/dhis2-docs#15]
https://www.dhis2.org/doc/snapshot/en/user/html/ch18s02.html
vs
https://www.dhis2.org/doc/snapshot/en/user/html/ch21.html#d5e3843

Table 18.1. Organisation unit identifiers supported for GML import
Matching priority	Identifier	Valid spellings	Guaranteed unique
1	Uid	uid, Uid, UID	Yes
2	Code	code, Code, CODE	No
3	Name	name, Name, NAME	No

vs

Currently, it is only possible to import GML data by matching on the name of the organisation unit itself. Therefore, if you have organisation units with the same name in your organisation unit hierarchy (e.g. two clinics with exactly the same name), you will need to distinguish them before importing GML. Otherwise, both organisation units may be updated with the same set of coordinates.

**Comment by grelland** [comment]
Thanks for reporting!
