### ISSUE TITLE
Mtn app: document "Legend set"

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/dhis2-docs#156]
New feature

Legend set creation and maintenance is moving to the Maintenance app. This needs to be documented.

**Comment by ceciliapersson** [comment]
Existing doc: http://dhis2.github.io/dhis2-docs/master/en/user/html/using_gis_legend_sets.html

**Comment by ceciliapersson** [comment]
First draft done: http://dhis2.github.io/dhis2-docs/master/en/user/html/ch10s08.html

**Comment by ceciliapersson** [comment]
Doc done: http://dhis2.github.io/dhis2-docs/master/en/user/html/ch10s09.html

**Comment by ceciliapersson** [comment]
http://dhis2.github.io/dhis2-docs/master/en/user/html/manage_legends.html
Perm. link

**Comment by rachbrooke** [comment]
@ceciliapersson 
Hi Cecilia, Just checked the mtn app doc and I could see the legend sets part you added but nothing about "color scales" - **color scales for legend sets**. Did you plan o adding this? See: https://docs.google.com/document/d/1RSlfbDJiGszkiBd6-b85ji4OeMsi79I_YN8xe_m1HPY/edit#heading=h.vya6wwwl0oem

Sorry for any confusion!

**Comment by ceciliapersson** [comment]
@rachbrooke No, I hadn't planned to add more info but I see that it could be valuable. Please go ahead and add this info.
