### ISSUE TITLE
GIS app: update doc with feedback from SME

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/dhis2-docs#159]
See e-mail from SME

**Comment by ceciliapersson** [comment]
Feedback:

14.3. Manage event layer

- "This layer lets you drill down from the aggregated data displayed in the thematic layers to the underlying individual events or cases.": I would add, "provided that events have associated GPS coordinates". Also mention, maybe, that it's possible to display aggregated events at the facility or boundary level, through a thematic layer using event data items. This can be useful when you don't have coordinates for events, but only for the org unit under which the events are recorded. 

- "You can use an element multiple times in your query by clicking Duplicate." - I don't think this is relevant or even possible, since you can only have one filter per variable. 

14.6.1. Create or modify a thematic layer

- "In the Data and periods section, select the data and periods you want to display." may need some more info here, or at the minimum highlight any differences with the pivot table and visualiser modules (e.g. one can't aggregate over multiple time periods, can't use category options as filters)

14.4. Manage facility layer

- Mention that the symbols of org unit groups are defined in the properties of each OU group (in Maintenance module)

14.7.1. Relocate a facility

- "The new coordinate is stored permanently.." - good to mention that this cannot be undone!

14.7.2. Swap longitude and latitude of a facility

- "Right-click a facility and click Swap lob/lat." - small typo here, and may need a bit more explanation - in short, this is useful if a facility falls outside the expected range because lat and long were swapped when the org unit was created.

**Comment by rachbrooke** [comment]
About the comment entered above (Cecilia):" Create or modify a thematic layer"
"In the Data and periods section, select the data and periods you want to display." may need some more info here, or at the minimum **highlight any differences with the pivot table and visualiser modules** (e.g. one can't aggregate over multiple time periods, can't use category options as filters) --> I have not restructured this section as **would be worthwhile to restructure the three areas concerned: GIS, pivot and visualizer and making the content consistent**.
