### ISSUE TITLE
Bug when multiple branches building at the same time

### ISSUE THREAD

**Issue by Markionium** [dhis2/dhis2-docs#16]
When multiple branches are building at the same time, the CI server might not push the updates for one of the build processes.

Not sure yet why this happens, might have something to do with trying to push, but had to pull before new commits. 

Perhaps doing a `git pull` before `git push` will solve the problem, and would be best practice.

**Comment by jason-p-pickering** [comment]
@Markionium is this still an issue? Have not see it recently, and not sure there is much we can do about it.

**Comment by ceciliapersson** [comment]
@Markionium Same question as Jason, is it still an issue?

**Comment by Markionium** [comment]
I guess we've updated the travis config since November 2015, which might have solved it. So lets just close it until it resurfaces. It hasn't happened for a while it seems.
