### ISSUE TITLE
Push Analysis

### ISSUE THREAD

**Issue by stian-sandvold** [dhis2/dhis2-docs#177]
Push Analysis

I'm using a couple of terms here:
	- PUSH ANALYSIS: An object in the system that works as a "blueprint" for generating a REPORT
	- REPORT: a report generated from a PUSH ANALYSIS

(As of now, there is no UI for creating, updating, viewing or deleting Push Analysis. This depends on Mark/Nicolai if they have time to add it to the maintenance app; UI for actually scheduling the Push Analysis will most likely be finished soon, will include link when it's done)

What is a Push Analysis?

A Push Analysis contains the following values:
	- Name
	- Message
	- Dashboard
	- UserGroups
	- Enabled
	- Last Run

How does Push Analysis work?

When running a Push Analysis, it compiles a list of recipients from the UserGroups, and for each user, generates a report. This report is based on the dashboard, and each of the dashboard items are generated specifically for this one user (So the data reflects the data the user has access to, or if the "user org unit" and similar options are set in the chart/map/reportTable, the users org unit is used). This means the all the users could get the same report(if all the data is "static") or reports custom to them (if all the data is "dynamic"), or a combination of the two.

These reports are sent by email. If a user is missing a valid email, or if something else goes wrong, no email is sent. In this case, the problem is also logged on the server.

The name and message of the Push Analysis are added to the reports. The name becomes the title of the report (and part of the title of the email containing the report) and the message becomes like a description that appears after the title in the report, as it's own paragraph.

Image of report:

![screen shot 2016-09-09 at 13 22 32](https://cloud.githubusercontent.com/assets/8579020/18385383/9a1dec9e-7690-11e6-9c9f-f6aa5f007320.png)

How can you use Push Analysis?

Currently, there are 3 ways to interact with existing Push Analysis:
	1. Using the api, you can render a preview of how the report would look like for you (/api/pushAnalysis/<uid>/render). Hopefully this can somehow be integrated in the UI in the future, but only the api can be used as of now.
	2. Using the api, you can run a single Push Analysis, which will compile a l list of user, create reports and send them as explained earlier.
	3. Using the scheduling UI (to be created), you can set up specified times at which ALL Push Analysis will run. The drawback of this, is that Push Analysis can only be sent automatically at the same intervals (eg. only weekly, daily, monthly, etc). Only Push Analysis that are enabled are sent using this method; If you want to send a Push Analysis that is disabled, you need to use option 2.

**Comment by stian-sandvold** [comment]
Just an update to the issue, as a few things have changed since I wrote this:

1. schedulingFrequency and schedulingDayOfFrequency are two new properties of the push analysis. These are respectively used to set a scheduling frequency (DAILY, WEEKLY, MONTHLY) and to set a day for scheduling in the chosen frequency (arbitrary for DAILY, 0-7 for WEEKLY (0 and 7 = sunday; this is just inherited from an underlying format, so we can just refer to them as 1-7 in the docs), 1-31 for MONTHLY). One thing that should be explicitly mentioned, is that if a push analysis is scheduled for 31 MONTHLY, the job will not run if the month has less than 31 days.

2. Mark is working on the maintenance app and including push analysis there. There will not be a separate UI for scheduling, as scheduling will be done implicitly when adding/updating/deleting push analysis.

3. These new changes makes item #3 in the last list of the original post outdated, since we wont be using that system after all. Scheduling will  now be done as described in this list.

4. Name value is no longer included in the email. instead, name will be used to identify the push analysis object in the system, the same as how "name" is used for other identifiable objects in the system; Instead, we now have a "title" value, which will be the title included in the report. This way a report can be named one thing, and the title of the report can be another.

**Comment by ceciliapersson** [comment]
Doc mostly done: http://dhis2.github.io/dhis2-docs/master/en/user/html/manage_scheduled_reports.html

Pending example and two new features: run & preivew

**Comment by ceciliapersson** [comment]
Doc done
https://dhis2.github.io/dhis2-docs/master/en/user/html/manage_push_reports.html
