### ISSUE TITLE
Mtn app: add doc about "Setup external map layer"

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/dhis2-docs#203]
Used from the GIS app, see PR #167

**Comment by rachbrooke** [comment]
Quick question about external maps: could you send me two examples of the most well-known external sources?

bjorn [2:01 PM]  
https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

bjorn [2:02 PM]  
XYZ overlay tiles: https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_only_labels/{z}/{x}/{y}.png

[2:02]  
This is place names that can be put on top of thematic layers

[2:03]  
WMS:  http://agsc.pdc.org/arcgis/services/global/pdc_basemap/MapServer/WMSServer

[2:03]  
Then you need to add layers in addiition: Countries,Time_Zones

**Comment by ceciliapersson** [comment]
Doc done, refer to: http://dhis2.github.io/dhis2-docs/master/en/user/html/ch10s12.html
(Note! Doc links are not permanent)

**Comment by ceciliapersson** [comment]
id tag added, link is not permanent:
http://dhis2.github.io/dhis2-docs/master/en/user/html/manage_ext_maplayer.html
