### ISSUE TITLE
Data visualizer issues

### ISSUE THREAD

**Issue by nicolayr** [dhis2/dhis2-docs#220]
- [ ] **13.2 Create a chart:** `"Last 12 Months from the period dimension [...] are selected by default"`: The default period type can be changed in the system settings, "Default relative period for analysis".

**Comment by ceciliapersson** [comment]
Hi Rachael,
Could you address this issue? 
Thanks Cecilia

**Comment by rachbrooke** [comment]
@ceciliapersson sure
