### ISSUE TITLE
Fix Excel trademark issues

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-docs#24]

**Comment by jason-p-pickering** [comment]
Suggest leaving this for now, as there do not seem to be hard and fast rules on when to apply this. 

http://grammar.yourdictionary.com/punctuation/where-do-you-put-quotes-when-using-a-registered-trademark.html


We can fix it if you think its really required, but it does not seem to be universally applied in non-commercial literature.  

What do you think @ceciliapersson @rachbrooke ?

**Comment by ceciliapersson** [comment]
In general, you're supposed to mark trademarks and registered trademarks that are not your own. From my experience, some companies really insist on this, others don't care that much. 
In any case, we need to decide on a common approach for the DHIS 2 documentation and be consistent throughout. Up until now I've seen both marked and unmarked trademarks in the user documentation.
