### ISSUE TITLE
Program management: document program notifications

### ISSUE THREAD

**Issue by grelland** [dhis2/dhis2-docs#266]
For 2.25 we're replacing 'tracked entity instance reminders' with 'program notifications'. They're conceptually very similar but also have a few differences.

Program notifications are configured for Program (program notification) and Program Stage (program stage notification), and are currently accessible from the context menu of these (like everything else...).

Docs for the existing feature (which we're replacing) is in the implementation guide under 'Program template reminders' (great name!!).

More detailed information on program notifications will come [here] soon.

**Comment by ceciliapersson** [comment]
@grelland Could you send me an example of a complete message template? Thanks

**Comment by ceciliapersson** [comment]
@grelland First draft done: https://dhis2.github.io/dhis2-docs/master/en/user/html/program_notifications.html
We can review it together tomorrow.

**Comment by grelland** [comment]
Here's a list of the variables available for P/PS notifications:

*Program* notifications:

* `V{program_name}` -> Program name
* `V{org_unit_name}` -> Organisation unit name
* `V{current_date}` -> Current date

*Program stage* notifications:

* `V{program_name}` -> Program name
* `V{program_stage_name}` -> Program stage name
* `V{org_unit_name}` -> Organisation unit name
* `V{due_date}` -> Due date (of the event)
* `V{days_since_due_date}` -> (Elapsed) days since due date
* `V{days_until_due_date}` -> Days until due date
* `V{current_date}` -> Current date

**Comment by ceciliapersson** [comment]
Doc done:
https://dhis2.github.io/dhis2-docs/master/en/user/html/program_notifications.html
