### ISSUE TITLE
Program: Event expiry days

### ISSUE THREAD

**Issue by abyot** [dhis2/dhis2-docs#286]
https://blueprints.launchpad.net/dhis2/+spec/lock-completed-events-after-expiry-days

https://blueprints.launchpad.net/dhis2/+spec/lock-time-periods-new-events

**Comment by ceciliapersson** [comment]
Do done:
https://dhis2.github.io/dhis2-docs/master/en/user/html/manage_tracker_programs.html#d0e23955
See steps 3. j and 3.k.
