### ISSUE TITLE
Messages (tickets) can be assigned to a user

### ISSUE THREAD

**Issue by stian-sandvold** [dhis2/dhis2-docs#337]
In addition to the previous features that enhance the "tickets" (MessageConversations) like priority, status and internal messages - A new enhancement has been added: Assign to user.

Technical:
So all messages that are interpreted as "tickets" (the message has a status associated with it) can now be assigned to a user. The only users that can be assigned to a ticket are users in the "feedback recipients" group (This is just a system setting so the actual name of the group can vary). A ticket can also be assigned to "none", which means no user is currently assigned to the ticket.

Visual addition and changes:
In the message inbox, a new button has been added. This button which is labeled "Assigned to me" or "All messages", conditional to if the button has been clicked or not. When clicking "Assigned to me", the inbox will only show messages where the logged in user is assigned, and the button will change to "All messages". "All messages" will list all messages as usual.

In the message-view, where you read the actual message, the layout have been changed. Instead of having all the ticket-related buttons on the top like before, all the ticket related buttons are now contained in a small "box" on the right hand side of the messages. The new dropdown "Assign to" has been added to this box, an it lists eligible users to be assigned, including the current assigned user. In addition to this, the dropboxes themselves no longer state the property it changes (Earlier, it said for example "Status: Open", "Status: Closed" etc for each option in the dropdown, while now, there is first a label "Status:" then the dropdown only contains "Open", "Closed", "Invalid", etc.

Remember:
All of the ticket-related actions like assigning users, setting priority and status and internal messages ALL DEPEND on whether the logged in user has the correct authorities to manage tickets and if the message viewed is a ticket or not.

![screen shot 2016-10-13 at 14 45 13](https://cloud.githubusercontent.com/assets/8579020/19349531/c01db112-9153-11e6-8adb-9661a7742d9b.png)

**Comment by ceciliapersson** [comment]
@stian-sandvold Is this for 2.25?

**Comment by stian-sandvold** [comment]
Jira issue here: https://jira.dhis2.org/browse/DHIS2-156

**Comment by ceciliapersson** [comment]
Existing user doc: https://ci.dhis2.org/docs/master/en/user/html/dashboards_messages.html

**Comment by ceciliapersson** [comment]
See PR: https://github.com/dhis2/dhis2-docs/pull/413

**Comment by ceciliapersson** [comment]
Doc updated: https://ci.dhis2.org/docs/master/en/user/html/dashboards_messages.html
