### ISSUE TITLE
System Settings app: Cache ( Cacheability ): public or private

### ISSUE THREAD

**Issue by stian-sandvold** [dhis2/dhis2-docs#338]
In addition to the existing system setting "cache strategy" which decides the age a cache can reach before it should be replaced, we now have the option to set the cacheability of the cache. 

The term cacheability was taken from this source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

This source also explains the public/private Cache Control stuff if you need more info about it.

Basically it does the following:

If a webpage is marked with Cache-Control: public:
Any node/server between the DHIS2 server and the enduser which has the ability to cache can cache this webpage. This is usually fine since that relives the traffic to the DHIS2 server and potentially speeds up the subsequent page loading speed.

If a webpage is marked with Cache-Control: private:
Any node/server between the DHIS2 server and the enduser which has the ability to cache can NOT cache this webpage. This is useful if the page served can or do contain sensitive information, which you don't want to be lying around on any random server. This means that each time you want a page like this, either you get a new page from the DHIS2 server, or the DHIS2 server caches the page. No other server than the DHIS2 server are allowed to cache it.

Not sure if this option is present in the system settings app yet, but I have informed Nico and it should be fixed :)

**Comment by ceciliapersson** [comment]
@stian-sandvold Is this new feature included in 2.25?

**Comment by ceciliapersson** [comment]
@stian-sandvold or @nicolayr  Could you add a link to the "dev" issue? I can't find it on the System Settings app repo:
https://github.com/dhis2/settings-app/issues

**Comment by stian-sandvold** [comment]
@ceciliapersson https://jira.dhis2.org/browse/DHIS2-258

**Comment by ceciliapersson** [comment]
User guide is up-to-date.
