### ISSUE TITLE
Support for more data types in analytics

### ISSUE THREAD

**Issue by stian-sandvold** [dhis2/dhis2-docs#346]
First: I'm not sure this is worth documenting, but I though i'd post it here anyway to let you guys decide :)

So previously in analytics, some data was stored in text-format in the analytics table, making it possible to see these values in analytical queries (for example using the pivot table). The types of data stored was mainly data identified as text, letters, coordinates and time.

Now, in addition to these, date, datetime, username, email and phone numbers are now also stored here.

These types i'm referring to are the types people describe their data as in the system.

**Comment by ceciliapersson** [comment]
@stian-sandvold Thanks for letting us know, we'll look into it :)

**Comment by ceciliapersson** [comment]
@stian-sandvold Could we have a look at this issue tomorrow, Wednesday? I need some more info about the type of user that would use this feature.

**Comment by stian-sandvold** [comment]
@ceciliapersson Sure, but I don't think documentation is needed after all - we can talk about it today :)

**Comment by ceciliapersson** [comment]
Closing issue since it doesn't need API or user doc.
