### ISSUE TITLE
Link to correct source for webapp.manifest documentation

### ISSUE THREAD

**Issue by Fredr1kh** [dhis2/dhis2-docs#347]
There are notable differences between the example in the manifest.webapp example in the section regarding [creating apps](https://dhis2.github.io/dhis2-docs/master/en/developer/html/dhis2_developer_manual_full.html#apps_creating_apps), and the actual working draft/spec from W3.
The documentation does not honor the members present in the W3 draft and as such it should be linked to the correct source at MDN on which the example is based on.

Please update the manifest.webapp section with the correct link to specification used, that can be found at the [MDN Archive of Obsolete Content](https://developer.mozilla.org/en-US/docs/Archive/Firefox_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest).

**Comment by ceciliapersson** [comment]
Hello,
Thanks for your feedback! I've talked to the devs and gotten the information that the standard isn't really useful to our case anymore. The initial idea was probably to use the standard but that hasn't been followed up. I've removed the link referring to the standard, see pull request: https://github.com/dhis2/dhis2-docs/pull/369

Kind regards,
Cecilia
Technical writer for DHIS2
