### ISSUE TITLE
Aggregation types

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-docs#36]
http://dhis2.github.io/dhis2-docs/master/en/user/html/ch05.html#dataElement

does not include all aggregation types for data elements

![image](https://cloud.githubusercontent.com/assets/2968061/15533945/fb4c453e-2266-11e6-806a-c9f128eb9780.png)

**Comment by ceciliapersson** [comment]
Thanks for the feedback. Working on the Maintenance app and all its relevant content right now, see docinprogress branch. I'll make sure to have the list of aggregation types completed.

**Comment by ceciliapersson** [comment]
Hi,
The aggregation types have changed for 2.25 release, see attached screenshot. These types have been documented.

![aggregationtypes](https://cloud.githubusercontent.com/assets/18207911/18839880/e28ebb46-840c-11e6-9a0a-c0a2ecdcae22.png)
