### ISSUE TITLE
SMS documentation has several markdown mistakes

### ISSUE THREAD

**Issue by jaboto** [dhis2/dhis2-docs#364]
While reviewing the SMS configuration document (https://github.com/dhis2/dhis2-docs/blob/master/src/commonmark/en/content/user/mobile.md) I realized that there are many mistakes (probably due to a conversion to Markdown) i.e. `****Feedback:****` instead of `**Feedback:** `.

In GitHub they are displayed properly but not in the generated doc: https://docs.dhis2.org/2.33/en/user/html/dhis2_user_manual_en_full.html#mobile_sms_command

**Comment by larshelge** [comment]
Thanks @jaboto. Would you be willing to provide a PR against master which fixes these issues?
