### ISSUE TITLE
Clarify use of trademark symbols

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-docs#37]
It seems we should use the trademark symbol the first time a trademark is mentioned. Clarify this and fix it in the docs.

**Comment by ceciliapersson** [comment]
At least the first time in every topic. A topic might be used in several places in the doc structure.

**Comment by jason-p-pickering** [comment]
Closing this for now, as I think Ceclia has provided the necessary instructions to how we should proceed with this. Really more of a editing issue at this point.
