### ISSUE TITLE
DHIS UG > Setting up GIS > Importing coordinates: Update link as requested

### ISSUE THREAD

**Issue by ceciliapersson** [dhis2/dhis2-docs#40]
Request from user received 4th Jul 2016:
Dear DHIS2 collaborator,
Regarding revision 2265	2016-06-02 14:27:45 Version 2.24 of the english user manual, there is a small update required.
The URL for MapShaper in section 18.2
http://dhis2.github.io/dhis2-docs/master/en/user/html/ch18s02.html
is currently:
http://mapshaper.com/test/MapShaper.swf
and it should become:
http://www.mapshaper.org/

Not sure what the best way is for reporting such as I could not find any suggest process, or failed to find it.

Kind regards
Kristof

**Comment by jason-p-pickering** [comment]
They can submit an issue or pull request.



On Thu, Jun 16, 2016 at 3:35 PM, Cecilia Persson <notifications@github.com>
wrote:

> Request from user received 4th Jul 2016:
> Dear DHIS2 collaborator,
> Regarding revision 2265 2016-06-02 14:27:45 Version 2.24 of the english
> user manual, there is a small update required.
> The URL for MapShaper in section 18.2
> http://dhis2.github.io/dhis2-docs/master/en/user/html/ch18s02.html
> is currently:
> http://mapshaper.com/test/MapShaper.swf
> and it should become:
> http://www.mapshaper.org/
>
> Not sure what the best way is for reporting such as I could not find any
> suggest process, or failed to find it.
>
> Kind regards
> Kristof
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhis2/dhis2-docs/issues/40>, or mute the thread
> <https://github.com/notifications/unsubscribe/AC1J_cULd226hxbQnxzy0716QjfZ-1BVks5qMVEugaJpZM4I3ZCr>
> .
>



-- 
Jason P. Pickering
email: jason.p.pickering@gmail.com
tel:+46764147049
