### ISSUE TITLE
Docker guide lacks information about user/pass

### ISSUE THREAD

**Issue by eloekset** [dhis2/dhis2-docs#506]
I've successfully started the dev cluster following the DHIS2 Docker guide: https://developers.dhis2.org/guides/dhis2-docker

What is the default username and password to log in to the DHIS2 application? Or where can I find it?
![image](https://user-images.githubusercontent.com/791721/90976056-3ea3af80-e53a-11ea-9075-aa57d3589295.png)

**Comment by teleivo** [comment]
Hi @eloekset did you manage to login?

I am not sure where the guide you linked to went. I get a page not found. This page https://developers.dhis2.org/docs/#starting-a-local-dhis2-instance does state username/password. I think it's using demo data from here https://dhis2.org/downloads/ which should also have a user with the same credentials.
