### ISSUE TITLE
Need access to the Dhis documentation repo for adding documentation about Metadata Sync feature

### ISSUE THREAD

**Issue by vanyaseth** [dhis2/dhis2-docs#51]

**Comment by jason-p-pickering** [comment]
Please just clone thus repo and Issue a pull request. If you have any specific questions, let us know.

**Comment by vanyaseth** [comment]
Hi Jason

I saw that line later about being able to clone and then issue a pull
request.

Already done!

sorry for the spam.

Regards
Vanya

On Thu, Jun 23, 2016 at 2:48 PM, Jason Pickering <notifications@github.com>
wrote:

> Please just clone thus repo and Issue a pull request. If you have any
> specific questions, let us know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhis2/dhis2-docs/issues/51#issuecomment-227994571>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANhQdVw3tPG3UgYVhXeE4-r3kUA8WTXWks5qOk9lgaJpZM4I8fCb>
> .
>



-- 
With Regards
ThoughtWorks Technologies
Hyderabad

--Stay Hungry Stay Foolish!!
