### ISSUE TITLE
broken links to relationship_model

### ISSUE THREAD

**Issue by gassims** [dhis2/dhis2-docs#924]
All the links in the doc page: https://docs.dhis2.org/en/use/user-guides/dhis-core-version-master/configuring-the-system/programs.html which link to relationship model seem to be broken. They refer to https://docs.dhis2.org/en/use/user-guides/dhis-core-version-master/configuring-the-system/relationship_model#relationship_model_relationship_type which is not in the same URL path as the page, and I think they should refer to this page: https://docs.dhis2.org/en/use/user-guides/dhis-core-version-master/understanding-the-data-model/relationship-model.html?

Thanks!

**Comment by Philip-Larsen-Donnelly** [comment]
Fixed. Should be in next build.
